# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(Build.SourceBranchName)
  displayName: 'Echo branch name'

- script: rm azure-pipelines.yml
  displayName: 'Remove pipelines file from clone'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: $(Build.SourceBranchName)
    contents: '**'
    targetFolder: '/etc/nginx/sites-enabled'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: $(Build.SourceBranchName)
    runOptions: 'commands'
    commands: 'service nginx reload'
    readyTimeout: '20000'